name: Deploy to Replicate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Cog
      uses: replicate/setup-cog@v2
      with:
        token: ${{ secrets.REPLICATE_API_TOKEN }}
        
    - name: Push to Replicate
      run: |
        cog push r8.im/${{ secrets.REPLICATE_USERNAME }}/video-merger
